language: node_js
node_js:
- 6.2
deploy:
  provider: heroku
  api_key:
    secure: ZRC30kGfssLG/rnL9q/bYsYtKkVa+JikVOUhOcMrGAPIXZbKsN15FKrE9S9URO905r1P6lW/yrc/9PpJvtw7vGPaxAZZEYQIeo63qTzzuGKgdMQ0wkBwXGfPCz0QVwwV/OMpVi3YWKvnwYp51burl1L0KFBryypV68BLeCKaBcZPuxTOodGWQ9ifr4R85dD8QC7WnmwA0Gz/nk7a8LQJgk4ioe6mEYWqjhSKHopXpHuGa4fmoDAghoSOQISpMMK0Pl7x044r1YHdTSXejhX6QtF9i4/bNLWMSDF0p56MovnwDuD0KFuKpgJINkezyWvgaE81OS0QIGEk41e6vyS7+w+HCgsHDpPWyXrNBRLHQYSDojRn+K5sJJ7QyJmkkVoFfxMjuks4eJMVZa6A3AqawHHr5idbnaWrEduwxzjd/1UsKTdph2NI+WVObD54V4Jz8RnpjKKTrm0F3/hViOEY/a3JT2Tr0eEzmLP1vKc7s3wgjqvR/Nj2LiNKJNLNl3s9qbyV602tlLfCLe4xwl5fOerlSlB8yMPqdl2OJDc1rMi9sGweYcAWlu7DMufrCNK3f2PNqNoJZYMj8kZFx4KUGrU6jPRm72qwBBuAugOgPJ5ic6IUPYx0vEeldIfosI0+hQLintxnvJIOALHV7gbSypXjHm/cLBsIUSNJ4/LFsB4=
  app: in-theaters
